#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Apr 25 18:53:08 PDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fibonacci_v1_tb_behav -key {Behavioral:sim_1:Functional:fibonacci_v1_tb} -tclbatch fibonacci_v1_tb.tcl -view /home/oliver/Documents/fpga_prototyping_sv_examples/6.5.3_fibonacci_1/vivado/fibonacci_v1/fibonacci_v1_tb_behav.wcfg -log simulate.log"
xsim fibonacci_v1_tb_behav -key {Behavioral:sim_1:Functional:fibonacci_v1_tb} -tclbatch fibonacci_v1_tb.tcl -view /home/oliver/Documents/fpga_prototyping_sv_examples/6.5.3_fibonacci_1/vivado/fibonacci_v1/fibonacci_v1_tb_behav.wcfg -log simulate.log

